DATASET:
  build_wrkspce: True
  new_train_test_split: True
  train_split_ratio: 0.7
  raw_dataset: "data/processed-dataset/aquash-monitoring-ADP"
  workspace: "artifacts/workspace"
  img_sz: 16 # resizing image into square image of size  img_sz X img_sz dimension
  dev: True # generate small data size for development purposes
  dev_size: 50 # size dev-dataset

MODEL:
  model_name: "FasterRCNN_ResNet50"
  model_dst: "artifacts/models"

TRAIN:
  transfer_learning: False # enable transfer learning
  num_epoch: 1 # number of epochs
  N_split: 1 # number of times the num_epoch will run
  lr_scheduling: True # enable learning rate (lr) decaying wrt training epochs
  step_size: 3 # lr_scheduling param1
  gamma: 0.1 # lr_scheduling param2
  momentum: 0.9 # learning momentum
  weight_decay: 0.0005 # learning decay weight
  num_workers: 0 # num workers
  verbose: False # Enable outputs display. It must be False if you are using a cluster

  # Hyper-parameters
  es_patience_ratio: [3] #This is required for early stopping, the number of num_epoch we will wait with no improvement before stopping
  batch_size: [4] # batch size
  lr: [0.005] # learning rate
  optimizer: ["SGD"] #,'adam']                        # learning optimizer

INFERENCE:
  inference_dst: "artifacts/inference"
