name: Build & Test Python codes
on: [push]
# on:
#   release:
#     types: [published]

env:
  PYTHON_VERSION: "3.8"

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt;fi

      - name: Link with flake8 [debugging python syntax]
        run: |
          # # stop the build if there are Python syntax errors or undefined names
          # flake8 . --count --select=E9,F63,F7,F82 --ignore=F541,E402,W503 --show-source --statistics
          # # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # flake8 . --count --ignore=F541,E402,W503 --max-complexity=20 --max-line-length=127 --statistics

      - name: Test the code using Pytest
        run: |
          # pip install pytest
          pwd
          echo "---------------------------------------------------"
          python tests/test_variables.py
          echo "---------------------------------------------------"
          # TODO: code how to skip tests which do not work on github actions
          echo "Some Pytest might be ignored, because it does not work with GitHub action"
          python -m pytest --verbose

  # build_test2:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #   - name: Test with pytest
  #     run: |
  #       pip install pytest pytest-cov
  #       pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
