name: Data Exploration
# on: [push]
on:
  release:
    types: [published]

jobs:
  cml_train2:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Setup the environment
        run: |
          # install packages
          pip install -r requirements.txt

      - name: Data exploration pipeline
        run: |
          # apply the ML workflow
          python src/data_exploration.py

      # - name: Write CML report
      #   env:
      #     REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # Post reports as comments in GitHub PRs
      #     cat results.md >> report.md
      #     cml comment create report.md
